### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by RainbowZephyr** [DopustimVladimir/atom-coffee-autocompile#10]
Atom tells me the file is compiled in the bottom, however when I open the JS file all that is inside it is, undefined. The file compiles correctly however coffee command in terminal.

**Comment by spike008t** [comment]
Same issue for me (atom 1.8.0 & latest version of atom-coffee-autocompile)

**Comment by kdkasad** [comment]
The same happens for me. I'm using the latest versions of Atom and coffee-autocompile.

**Comment by iainhouston** [comment]
Seems to compile to "undefined" if you don't choose `sourcemap: true`

**Comment by DopustimVladimir** [comment]
Thats because of old uglify-js plugin. Fixed. See #13
