### ISSUE TITLE
Suddenly stopped compiling on save

### ISSUE THREAD

**Issue by tvld** [DopustimVladimir/atom-coffee-autocompile#12]
Used to work flawless, but suddenly it does not compile automatically anymore...

Ubuntu 17.10 / Atom 1.24.1 / v0.6.2

Is there some config missing I should have done? The .coffee files did not change...

**Comment by tvld** [comment]
ok, placing a ``coffee-compile.cson`` in the projects home containing:
```
compileOnSave: true
```
Did the trick... no idea why I never needed that before ? )))

**Comment by tvld** [comment]
Strike that... again same problem - no auto compile upon save.... It's unstable... Any idea how to find the culprit?

**Comment by tvld** [comment]
Still no solution... Nobody has a tip?

**Comment by masterbee** [comment]
@tvld - can agree this is an issue for me as well. @olmokramer any idea how to fix? It would be a shame to move off to another coffee compile plugin, I really like the in file settings approach since it helps my projects a lot.

**Comment by olmokramer** [comment]
Sorry for the late response, I haven't maintained this plugin for a few years and I don't intend to in the future. I'm sorry. If anyone wants to take over, please let me know and I'll happily hand over the repository.
